### PR TITLE
add eventsChain1 testCreateNewRecord

### PR DESCRIPTION
**Pull request by MariaMoroz**
https://trello.com/c/EZ5XIxGL/778-at28javascript-entity-events-chain1-create-new-record

### CODE REVIEW

**Review by LMalushkina — APPROVED** [review]

**Review by gmirzoyan — APPROVED** [review]

**Comment by TupakAmaru13** [comment]
Good job

**Review by TupakAmaru13 — COMMENTED** [review]
Good!

**Review by SamJulia — APPROVED** [review]

**Review by TupakAmaru13 — APPROVED** [review]
GooD job!

**Review by Lizzzzi — COMMENTED** [review]
looks good for me!

**Review by Vladyslavva — APPROVED** [review]

**Review by TupakAmaru13 — COMMENTED** [review]
Good

**Pull request merged**
